"""
Learning material Pydantic models for FriendOS Phase 2.
Covers topics, diagnostic questions, and the overall material document.
"""

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class Topic(BaseModel):
    """A single learning topic extracted from study material."""
    name: str
    description: str
    difficulty: str = "beginner"  # beginner | intermediate | advanced

    @field_validator("difficulty")
    @classmethod
    def validate_difficulty(cls, v: str) -> str:
        allowed = {"beginner", "intermediate", "advanced"}
        v_lower = v.lower().strip()
        if v_lower not in allowed:
            raise ValueError(f"difficulty must be one of {allowed}, got '{v}'")
        return v_lower


class DiagnosticQuestion(BaseModel):
    """A multiple-choice diagnostic question generated by Gemma."""
    question: str
    options: list[str] = Field(..., min_length=4, max_length=4)
    correct_answer: int = Field(..., ge=0, le=3)
    topic: str
    difficulty: str = "beginner"

    @field_validator("difficulty")
    @classmethod
    def validate_difficulty(cls, v: str) -> str:
        allowed = {"beginner", "intermediate", "advanced"}
        v_lower = v.lower().strip()
        if v_lower not in allowed:
            raise ValueError(f"difficulty must be one of {allowed}, got '{v}'")
        return v_lower


class GemmaAnalysisOutput(BaseModel):
    """
    Schema that Gemma's JSON response MUST conform to.
    Used for Pydantic validation of raw AI output.
    """
    title: str
    topics: list[Topic] = Field(..., min_length=1)
    diagnostic_questions: list[DiagnosticQuestion] = Field(
        ..., min_length=5, max_length=10
    )


class LearningMaterialInDB(BaseModel):
    """Document stored in the learning_materials MongoDB collection."""
    filename: str
    page_count: int
    extracted_text_preview: str = Field(
        default="",
        description="First ~2000 chars of extracted text for reference",
    )
    title: str
    topics: list[Topic]
    diagnostic_questions: list[DiagnosticQuestion]
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class MaterialUploadResponse(BaseModel):
    """Response returned after successful PDF upload and analysis."""
    success: bool
    material_id: str
    title: str
    topics: list[Topic]
    diagnostic_questions: list[DiagnosticQuestion]


class MaterialDetailResponse(BaseModel):
    """Response for GET /api/material/{material_id}."""
    material_id: str
    filename: str
    page_count: int
    title: str
    topics: list[Topic]
    diagnostic_questions: list[DiagnosticQuestion]
    created_at: datetime
